x--expand-yaml-anchors--remove:
  - &default-job
    runs-on: ubuntu-latest

  - &checkout
    name: Checkout sources
    uses: actions/checkout@v2

  - &toolchain
    profile: minimal
    toolchain: nightly
    override: true

  - &install-toolchain
    name: Install toolchain
    uses: actions-rs/toolchain@v1
    with: *toolchain

name: CI
on: [push, pull_request]

jobs:
  check:
    <<: *default-job
    name: Check
    steps:
      - *checkout
      - *install-toolchain
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          
  test:
    <<: *default-job
    name: Test Suite
    steps:
      - *checkout
      - *install-toolchain
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  lints:
    <<: *default-job
    name: Lints
    steps:
      - *checkout
      - <<: *install-toolchain
        with:
          <<: *toolchain
          components: rustfmt, clippy
    
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
        
      - name: Run cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  cargo-deny:
    <<: *default-job
    name: Cargo Deny
    steps: 
      - *checkout
      - uses: EmbarkStudios/cargo-deny-action@v1
